### ISSUE TITLE
I wish I could change the menubutton to right click

### ISSUE THREAD

**Issue by vitorLostadaC** [sonnyp/Retro#3]
![image](https://user-images.githubusercontent.com/69974844/209134975-91b2f299-56d6-4598-9291-62ffa0760e7e.png)
to have a cleaner design I think it would be interesting to have this possibility
![image](https://user-images.githubusercontent.com/69974844/209135571-41c9b1c7-ab21-4aae-89eb-a7b64f7b17b6.png)
currently i am setting opacity 0 but it is not aesthetic

**Comment by sonnyp** [comment]
yeah I was a bit annoyed with this menu and where to put it

We can't hide it by default because it's the only way to discover the options. 

Perhaps we could have a "Hide menu button" setting that shows a popup 'You can access the menu by right clicking'.

@bertob wdyt?

**Comment by VitorLostada** [comment]
what if we put all menu options on the right button?

**Comment by bertob** [comment]
Maybe it could be shown as an overlay on hover? 

Monitorets does something kinda like that, it shows a headerbar on hover:

![image](https://user-images.githubusercontent.com/1908896/209409354-b15776e6-b4e3-47b4-9e27-3128e2f39e1a.png)

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Retro/pull/10

![image](https://github.com/sonnyp/Retro/assets/19673/dc575e9d-ab80-4c7d-8fe2-0c6d8a8877bd)
