### ISSUE TITLE
multiple virtual desktops

### ISSUE THREAD

**Issue by mhmoran** [sonnyp/Retro#7]
To make the app really useful, I need it to always be displayed on the current virtual desktop.  So is that a configuration option
somewhere that I'm missing?

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=21.1
DISTRIB_CODENAME=vera
DISTRIB_DESCRIPTION="Linux Mint 21.1 Vera"
Flatpak 1.12.7
5.19.0-43-generic #44~22.04.1-Ubuntu SMP

**Comment by sonnyp** [comment]
What makes you think this is a Junction bug and not your WM?

Works fine on GNOME
